### ISSUE TITLE
Question: Can we use Scatter auth on Dapp that is hosted on localhost ?

### ISSUE THREAD

**Issue by WendySanarwanto** [GetScatter/scatter-js#101]
Hello all,

I'd like to ask you whether we can use scatter authentication on our dapp whose the smartcontract is deployed and run on local private EOSIO node (hosted in localhost) and the front end is a ReactJS based web SPA, hosted on localhost as well. Can we do this ? If yes, what is the possible JSON values that I should pass as an argument of `ScatterJS.Network.fromJson` method ? 

Thanks.

**Comment by nsjames** [comment]
Really depends on where your local node is referenced to.

Here's an example of my localhost setup:
```
const network = Network.fromJson({
	host:'192.168.1.11',
	port:8888,
	protocol:'http',
	chainId:'cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f',
	blockchain:'eos',
});
```

**Comment by WendySanarwanto** [comment]
Thanks for your kind response, @nsjames 

I ran my `nodeos` on `localhost` or `0.0.0.0`, will it work if I set the host with these url ? Also, how did you get the `chainId` from ? is it from log message that is displayed on terminal/log when starting `nodeos` ?

**Comment by nsjames** [comment]
`0.0.0.0` just listens on all interfaces so likely you can just replace the host with `127.0.0.1` or `localhost`.

That `chainId` should work for your local too since it's the default `chainId` when no genesis is input. If not, then just do `cleos get info` and it'll tell you the `chainId` there.

**Comment by WendySanarwanto** [comment]
@nsjames Thank you , mate. I am going to try out and close this question :+1:
