### ISSUE TITLE
Now I can get the account id with scatterJS.However, if I want to add the identity of an account to my scatter wallet, is there any API for it

### ISSUE THREAD

**Issue by keyBM** [GetScatter/scatter-js#104]

**Comment by nsjames** [comment]
I'm not sure I understand the question. Can you give me a bit more information about what you are trying to do, and what you've already tried?

**Comment by keyBM** [comment]
Thank you by the way！
I want to create an EOS account with scatterJS and create an identity for the account in my scatter

**Comment by nsjames** [comment]
Sure, scatter-js and Scatter Desktop have flows which support that.

Here's the algorithm for it:
- `suggestNetwork(network)` [API Reference](https://get-scatter.com/docs/api-suggest-network) - This will allow you to add a network to the user's Scatter if not using mainnet.
- `getPublicKey('eos')` [API Reference](https://get-scatter.com/docs/api-get-public-key) - This will allow the user to either provide or generate a key for you to use.
- Create an account for the user in your backend with they public key. You don't want to do this on your front-end as it will give away your key obviously.
- `linkAccount(account, network)` [API Reference](https://get-scatter.com/docs/api-link-account) - Once an account is created you can use this to link the account to the user's Scatter.
- `login()` or `getIdentity()` - Now all you need to do is log in.

By doing it the way above you

**Comment by nsjames** [comment]
There is also an undocumented `ScatterJS.hasAccountFor(network)` which you can use before anything to check if the user already has an account for that network.

**Comment by keyBM** [comment]
Thank you very much！thank you！




On 03/14/2019 18:50, Nathan James wrote:

There is also an undocumented ScatterJS.hasAccountFor(network) which you can use before anything to check if the user already has an account for that network.
