### ISSUE TITLE
account missing issue with Scatter-desktop and exist on Scatter-Extension with a same settings

### ISSUE THREAD

**Issue by dacom-dark-sun** [GetScatter/scatter-js#11]
I communicate with separate EOS-compatible network and contract on it. Settings in Scatter-Desktop and Scatter-Extension is a full same. Both Scatters have imported keys, networks and pulled identities. 

 When i pull transfer action with enabled Scatter-Ex and closed Scatter-D, transfer is success, Scatter-Ex sign transaction. When i disable Scatter-Ex and open Scatter-D for the same transfer action, after submit permission, i have error:

`{ "type": "account_missing", "message": "You are trying to sign a request with an account that isn't currently linked or doesn't exist in the user's Scatter", "code": 402, "isError": true }`

Identity does not contain a account for sign. But account installed same like in Scatter-Ex. How it can be solved for stable operation two applications?
 
I use this code: 
```      
ScatterJS.scatter.connect("travelchain").then(connected => {
        if(connected){
            this.scatter = ScatterJS.scatter;
            window.scatter = null;
        }
    });

..............

scatter.getIdentity().then(identity => {
          const options = {
            authorization: this.username,
          }

          const eost = scatter.eos( network, Eos, options, 'https');
          eost.transfer(this.username, this.contract_name, amount, this.host_name).then(()=> {
            this.refresh_page()
            loading.close()
          }).catch(error => {
            this.throwBCError(error)
            loading.close()
          })
      })
```

**Comment by dacom-dark-sun** [comment]
After update Scatter-Ex, signature not provided too - just clean window with signature request. What i do wrong?

**Comment by nsjames** [comment]
This shouldn't work with either of them. 
You aren't requesting access to any EOS accounts within your `getIdentity()` call which should throw an error on both since your app doesn't have access to that information.

You should be calling `getIdentity({ accounts:[network] })` and then once that has resolved you should be putting the account name you got back into the transfer.


```
getIdentity({ accounts:[network] }).then(id => {
    const account = id.accounts[0];
   
    // Also, don't forget the authorization options so it can work with non-active permissions
    const options = { authorization:[`${account.name`@`${account.authority`] };

   eos.transfer( account.name, 'someaccount', '1.000 EOS', 'Memo', options );
});
```

**Comment by dacom-dark-sun** [comment]
Nice, it works. Thanks!
