### ISSUE TITLE
Improve performance of detecting connected state

### ISSUE THREAD

**Issue by liamcurry** [GetScatter/scatter-js#111]
This issue is based on my comment here https://github.com/GetScatter/ScatterDesktop/issues/245#issuecomment-484287668

I'm posting it again here for visibility and because I think it should be considered a separate issue related to `scatter-js`.

Currently it takes `scatter-js` ~5 seconds to determine if Scatter is available. It would be nice if this were under 1 second instead, AND if alternative ports were tried.

I think one approach to solve this problem could be to 'ping' the socket.io server with a simple HTTP request first, before attempting to connect with socket.io. This should allow detecting if Scatter is available much faster, and it should enable checking alternative ports within a reasonable time.

Some pseudo-code for how this would work:

```js
pingScatterServer(50005)
    .then(connectToSocketIo)
    .catch(() => {
        Promise.race([
            pingScatterServer(51005),
            pingScatterServer(52005),
            pingScatterServer(53005),
            pingScatterServer(54005),
            pingScatterServer(55005),
        ])
    })
    .then(connectToSocketIo)
    .catch(scatterNotAvailable);
```

I believe this function would change a bit:
https://github.com/GetScatter/scatter-js/blob/d82281fa4894f03a8c1551f79df80d59a79f1324/packages/core/src/services/SocketService.js#L78

I know socket.io supports HTTP transports so I imagine there should be some endpoint you can send a `HEAD` or `OPTIONS` request to.

**Comment by nsjames** [comment]
Scatter 11, with ScatterJS multi-port support now fixes this!
