### ISSUE TITLE
"@scatterjs/eosjs2" is referencing to "scatterjs-core" instead of "@scatterjs/core"

### ISSUE THREAD

**Issue by Viterbo** [GetScatter/scatter-js#123]
I'm in the process of integrating with EOS-Lynx wallet throw ScatterJS.

In the [githug page](https://github.com/GetScatter/scatter-js) says: 
Installation: `npm i -S @scatterjs/core @scatterjs/eosjs2 eosjs@20.0.0`

but the compiler throws this error in console:
```
ERROR in ./node_modules/@scatterjs/eosjs2/dist/index.js
Module not found: Error: Can't resolve 'scatterjs-core' in '/var/www/lynx-angular-scatterjs/node_modules/@scatterjs/eosjs2/dist'
```
I went to ./node_modules/@scatterjs/eosjs2/dist/index.js and replaced the string "'scatterjs-core" with "@scatterjs/core" and worked good!

**Comment by nsjames** [comment]
Whoops :)
Thanks for the report, fixing now.

**Comment by nsjames** [comment]
baab05c4e85b8841c051675dcccfa4e19caf9dcd

Fixed and uploaded to npm
