### ISSUE TITLE
 ScatterJS.identity is null without auto-filled when logged in and then refreshing page

### ISSUE THREAD

**Issue by fire-xyz** [GetScatter/scatter-js#125]
hi, maybe it's solved issue before, but i didn't find a solution for me.
I tried to use Scatter Desktop with my website. I used latest scatter-js, eosjs@16
I noticed - "After a successful login, the "Identity" will be available at ScatterJS.identity. If a user refreshes the page and has already logged in, the ScatterJS.identity property will be auto-filled.". However, I found that it works when I used Chrome Extension plug-in, if I disabled Extension plug-in, and used Scatter Desktop, it can login/logout via Scatter Desktop correctly without refresh the page, but if logged in and refreshes the page, ScatterJS.identity will be null again (without auto-filled) 
Does the ScatterJS.identity auto-filled for Scatter Desktop, needs local connection between browser and scatter desktop? Everytime I refreshed, i can see the browser console has errors such:

GET http://127.0.0.1:51505/ net::ERR_CONNECTION_REFUSED
GET http://127.0.0.1:53005/ net::ERR_CONNECTION_REFUSED
GET http://127.0.0.1:54505/ net::ERR_CONNECTION_REFUSED
GET https://local.get-scatter.com:54506/ net::ERR_CONNECTION_REFUSED
GET https://local.get-scatter.com:51506/ net::ERR_CONNECTION_REFUSED
GET https://local.get-scatter.com:53006/ net::ERR_CONNECTION_REFUSED
GET https://local.get-scatter.com:56006/ net::ERR_CONNECTION_REFUSED

**Comment by nsjames** [comment]
It definitely does use a local websocket for connections, but if those were all the errors you got then it looks like it found ports 50005 and 50006. 

I think this might just be a timing issue. Can you login, and then refresh the page, and then set a timeout for checking the identity after doing `ScatterJS.connect()`. Let's see if delaying the console.log shows the identity loaded.

**Comment by fire-xyz** [comment]
> It definitely does use a local websocket for connections, but if those were all the errors you got then it looks like it found ports 50005 and 50006.
> 
> I think this might just be a timing issue. Can you login, and then refresh the page, and then set a timeout for checking the identity after doing `ScatterJS.connect()`. Let's see if delaying the console.log shows the identity loaded.

@nsjames, ya, correct, it's about timing. thanks for the answer.

**Comment by iamcco** [comment]
Same issue, but i can't get identity after delay. @fire-xyz Can you share sample code ?

**Comment by iamcco** [comment]
I use the latest scatter-js and  eosjs@20.0.0

**Comment by fire-xyz** [comment]
> Same issue, but i can't get identity after delay. @fire-xyz Can you share sample code ?

for my case, before I get value of scatter.identity, i need to await the connection, for example:
    await checkConnect()
    return ScatterJS.identity

    async checkConnect(){
        this.connected = await ScatterJS.connect('scatter', {Network:this.network})
        return this.connected
    }

**Comment by iamcco** [comment]
@fire-xyz Thanks you.

I can't get identity with this way, too. maybe it's because I use the scatter-js2 and eosjs@20.0.0

**Comment by fire-xyz** [comment]
> @fire-xyz Thanks you.
> 
> I can't get identity with this way, too. maybe it's because I use the scatter-js2 and eosjs@20.0.0

I also updated to eosjs@20.0.0, it works fine
Maybe you can post

**Comment by fire-xyz** [comment]
> @fire-xyz Thanks you.
> 
> I can't get identity with this way, too. maybe it's because I use the scatter-js2 and eosjs@20.0.0

I also updated to eosjs@20.0.0, it works fine. I should use the same libs as yours. maybe you can post your codes

**Comment by iamcco** [comment]
I use the code below, when the page init use the `pageInit` function to connected to scatter and get login identity state. when user click login button then will use `scatterLogin` function to login.

It's wried that i can't identity after refresh the page.

``` typescript
import ScatterJS from '@scatterjs/core'
import ScatterEOS from '@scatterjs/eosjs2'
import { Api, JsonRpc } from 'eosjs'
import { BehaviorSubject, from, Observable, of, throwError } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';

ScatterJS.plugins(new ScatterEOS())

const network = ScatterJS.Network.fromJson({
  blockchain: 'eos',
  chainId: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906',
  host: 'nodes.get-scatter.com',
  port: 443,
  protocol: 'https'
})

class EosProxyService {
  private rpc = new JsonRpc(network.fullhost())
  private eosAccount$: BehaviorSubject<any> = new BehaviorSubject(undefined)
  private eos: any

  pageInit() {
    ScatterJS.connect(
      'MyApp',
      { network }
    )
      .then(connected => {
        if (connected) {
          setTimeout(() => {
            if (ScatterJS.identity) {
              // update eos account
              this.eosAccount$.next(ScatterJS.account('eos'))
              // get eos handle
              this.eos = ScatterJS.scatter.eos(
                network,
                Api,
                {
                  rpc: this.rpc,
                  beta3: true
                }
              )
              ;(window as any).ScatterJS = undefined
            }
          }, 2000)
        }
      })
      .catch(() => {})
  }

  scatterLogin (): Observable<boolean> {
    return from(
      ScatterJS.connect(
        'MyApp',
        { network }
      )
    ).pipe(
      switchMap(connected => {
        if (!connected) {
          return throwError({
            type: 'connected-fail',
            message: 'Connect to Scatter Failed!'
          })
        }
        return (!ScatterJS.identity
          ? from(ScatterJS.login())
          : of(ScatterJS.identity)
        ).pipe(
          map(() => {
            // update eos account
            this.eosAccount$.next(ScatterJS.account('eos'))
            // get eos handle
            this.eos = ScatterJS.scatter.eos(
              network,
              Api,
              {
                rpc: this.rpc,
                beta3: true
              }
            )
            ;(window as any).ScatterJS = undefined
            return true
          })
        )
      })
    )
  }
}
```

**Comment by iamcco** [comment]
It's wried that when i change my page to http protocol then I can get the identity after refresh the page.
