### ISSUE TITLE
fetch not defined in nodejs environment

### ISSUE THREAD

**Issue by mmcs85** [GetScatter/scatter-js#128]
In the new scatterjs version fetch is used on SocketService but on the nodejs environment is not defined. Maybe add a way to provide on Scatterjs initialization the fetch function?

Alternative is redefining it globaly:

import fetch from 'node-fetch'
(global as any).fetch = fetch

https://github.com/GetScatter/scatter-js/blob/53ba6562891c4ae7e580195c15f95c12077b069a/packages/core/src/services/SocketService.js#L152

**Comment by nsjames** [comment]
Shouldn't be needed. Add `isomorphic-fetch` into the project and require it in on the top level doc and it'll propagate throughout the environment.

**Comment by mmcs85** [comment]
thats reasonable, we should mention it as dependency for the nodejs env

**Comment by nsjames** [comment]
Yup good idea, 606dd7349622ac5efc81de832e24887a2582c842
