### ISSUE TITLE
Add a means to know when Scatter Desktop is locked or actually missing

### ISSUE THREAD

**Issue by acoutts** [GetScatter/scatter-js#13]
With Scatter web when I do the routine to check for Scatter, it will return that Scatter is found if their wallet is locked.

With Scatter Desktop and scatter-js, when I do the following routine to check for Scatter, I find that if the user only has Scatter Desktop (no chrome extension), and their wallet is locked, then this routine returns as failed and I can't differentiate between if the user is missing the Scatter app, or if it's just locked.

```javascript
    if (await ScatterJS.scatter.connect(`[APPNAME]`, { initTimeout: 5000 })) {
      this.setScatterInstance(ScatterJS.scatter)
      window.scatter = null;
    } else {
      console.log(`Did not find scatter instance on user's computer or browser`);
      this.setScatterState('missing');
    }
```

**Comment by nsjames** [comment]
This isn't actually possible since before a user logs into Scatter Desktop/Mobile there just is no socket server. Effectively it's never locked, just closed ( quit ) and you can't verify the existence of something which can't prove it's lack of existence.

**Comment by nsjames** [comment]
This might be something to consider for a SIP

https://github.com/GetScatter/SIPs
