### ISSUE TITLE
Error "navigator is not defined" in NodeJS

### ISSUE THREAD

**Issue by Buzhanin** [GetScatter/scatter-js#132]
npm install command:
> npm i -S @scatterjs/core @scatterjs/eosjs2 eosjs@20.0.0 @babel/runtime

Minimal code to replicate:

> const ScatterJS = require('@scatterjs/core');
> const ScatterEOS = require('@scatterjs/eosjs2');
> ScatterJS.plugins(new ScatterEOS());

Full Error Message:

> ReferenceError: navigator is not defined
>     at C:\Users\chper\Documents\Deployer\node_modules\device-uuid\lib\device-uuid.js:1036:27
>     at Object.<anonymous> (C:\Users\chper\Documents\Deployer\node_modules\device-uuid\lib\device-uuid.js:1038:3)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (C:\Users\chper\Documents\Deployer\node_modules\device-uuid\index.js:14:18)

"device-uuid" was added as dep in a0253339465e19a4fd4c9b53057a63d71e655f29

**Comment by nsjames** [comment]
I'm guessing you're running this in a nodejs environment?
We might have to add some `global.navigator` spoofing in there when the `window` object isn't present.

**Comment by Buzhanin** [comment]
> I'm guessing you're running this in a nodejs environment?
Yes. I wanted to use Scatter as a signature provider for a few of my nodejs scripts.

**Comment by nsjames** [comment]
Can you try out the latest version up on npmjs and let me know if it works?

**Comment by Buzhanin** [comment]
> Can you try out the latest version up on npmjs and let me know if it works?

It doesn't work. 
`global.navigator` should be assigned a value before `import {DeviceUUID} from 'device-uuid';`
And it looks like it shouldn't be assigned an empty object. Otherwise I get this error
```
TypeError: Cannot read property 'replace' of undefined
    at DeviceUUID.get [as parse] (C:\Users\chper\Documents\Deployer\node_modules\device-uuid\lib\device-uuid.js:981:38)
```

**Comment by nsjames** [comment]
`@scatterjs/core@2.7.37` fixes this, but relay sockets on nodejs will have a defaulted `nodejs_env` value for the time being as there isn't really a usecase for them yet.

There needs to be a way to align nodejs env device uuids and browser device uuids for there to be any connections there, in the future.
