### ISSUE TITLE
eosjs2 naming confusion

### ISSUE THREAD

**Issue by limulidae** [GetScatter/scatter-js#153]
after some research,
I realize that eosjs2 is referring to https://github.com/EOSIO/eosjs/releases/tag/20.0.0, not the archived https://github.com/EOSIO/eosjs2

**Comment by nsjames** [comment]
Yup, sadly this is legacy stuff as block.one overwrote their `eosjs` repository with another (`eosjs2`).
Changing it on our side now might break all CDN based dapps integrating
