### ISSUE TITLE
JSON parsing error when RelaySocket connect fails

### ISSUE THREAD

**Issue by gtolarc** [GetScatter/scatter-js#173]
The following is an error while calling UALProvider when using ual-reactjs-renderer in react app.
![스크린샷 2020-07-06 오후 3 00 29](https://user-images.githubusercontent.com/8623798/86560800-27186380-bf9a-11ea-9507-0d8793b24dae.png)
![스크린샷 2020-07-06 오후 3 00 47](https://user-images.githubusercontent.com/8623798/86560805-297abd80-bf9a-11ea-8df9-80ab1e6cc4e4.png)
If you follow the call stack, the error occurs in the connect part of RelaySocket.js of the scatterjs core. Can you guys solve it?

**Comment by gtolarc** [comment]
#174 Please review this PR :)

**Comment by nsjames** [comment]
merged, thanks for the fix! <3
