### ISSUE TITLE
When calling transact(eosio.msig), Firefox and Chrome caught exception that said firewalled.

### ISSUE THREAD

**Issue by fintechee** [GetScatter/scatter-js#177]
Hello everyone,

I hope you are doing well.

We encountered an issue.
When calling transact(eosio.msig's approve action), Firefox and Chrome both caught exception that said firewalled.
If the threshold were 2, the approve action got exception by either of actor. 
Even if the threshold were 1, the approve action got error(firewalled due to malicious) as well.
eosio.msig's propose and cancel actions are fine
If we use the eosjs's default signature provider for dev, all actions of eosio.msig are done successfully.

Please teach us to solve the problem.
Any advice would be appreciated, many thanks.

**Comment by nsjames** [comment]
Go into Scatter settings and disable the firewall. Approving msigs can be dangerous as they don't always say what they are.

**Comment by fintechee** [comment]
Thank you, it worked!!
