### ISSUE TITLE
Allow identities to set image URL 

### ISSUE THREAD

**Issue by jafri** [GetScatter/scatter-js#19]
Allow identities to set image URL and maybe telegram (please <3)

**Comment by liamcurry** [comment]
Yes or maybe an IPFS hash that points to an image. That would be a little more secure for devs to use than a plain URL, and then uploading an image to IPFS could be done all within Scatter.

**Comment by nsjames** [comment]
Let's add these to SIPs, since they don't belong anywhere yet.

https://github.com/GetScatter/SIPs
