### ISSUE TITLE
"npm install" returns error 

### ISSUE THREAD

**Issue by qlqllu** [GetScatter/scatter-js#20]
When I run `npm i scatter-js --save`, it returns this error:  ` Unexpected end of JSON input while parsing near '...},"modified":"2017-09'`, which causes I can't install the scatter-js.

I am using windows 8 and npm 5.6.0

**Comment by nsjames** [comment]
Looks like this is an npm issue. 
Try `npm cache clean --force`

**Comment by qlqllu** [comment]
After run `npm cache clean --force`, I still get this error: `Unexpected end of JSON input while parsing near '...ap":false,"directorie'`, this seems the same error.

**Comment by qlqllu** [comment]
I can install any other packages well.

**Comment by nsjames** [comment]
Very hard to debug this as I can't reproduce it. 
I'm waiting to see if some other devs have issues to we can try to find a pattern.
