### ISSUE TITLE
There is a problem with Path (Plugins -> plugins)

### ISSUE THREAD

**Issue by yepp4you** [GetScatter/scatter-js#21]
In the following two lines, plugins should be used instead of Plugins.

import Plugin from './Plugins/Plugin'; 
=> import Plugin from './plugins/Plugin';

import * as PluginTypes from './Plugins/PluginTypes';
=> import * as PluginTypes from './plugins/PluginTypes';

https://github.com/GetScatter/scatter-js/blob/483e2d328fa8f43ce7b5f4e9c3f587fb5d602614/packages/core/src/index.js#L3

https://github.com/GetScatter/scatter-js/blob/483e2d328fa8f43ce7b5f4e9c3f587fb5d602614/packages/core/src/index.js#L4

**Comment by nsjames** [comment]
68f4b91120393e079ec9b7317af4c80a4e431992
