### ISSUE TITLE
Publish package pre-compiled

### ISSUE THREAD

**Issue by devgg** [GetScatter/scatter-js#22]
I want to use the library with create-react-app and it fails to compile. Please publish the package pre-compiled so we can circumvent this issue ([link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)).

**Comment by Soleone** [comment]
I assume adding the babel runtime as a dev dependency fixes the issue:

https://github.com/GetScatter/scatter-js#nodejs-and-babelwebpack

Would you be okay with closing this issue with this new set up instruction in place?
