### ISSUE TITLE
Transpiling was not successful in ES2015. 

### ISSUE THREAD

**Issue by yepp4you** [GetScatter/scatter-js#23]
Transpiling was not successful in ES2015.
let, const, class reserved words are exposed. Babel's presets seem to be wrong.
Please check transpiling.

packages/core/dist
packages/plugin-eosjs/dist
packages/plugin-web3/dist

https://github.com/GetScatter/scatter-js/blob/73e2595159b46b83dcccc823dea480ca634e5b1c/packages/core/dist/index.js#L47

**Comment by Soleone** [comment]
I wonder if this is a similar issue that might now be obsolete, see https://github.com/GetScatter/scatter-js/issues/7#issuecomment-434901798
