### ISSUE TITLE
Did Scatter-JS support mobile application such as iOS, Android? 

### ISSUE THREAD

**Issue by shi1234ww** [GetScatter/scatter-js#24]
Hi, My boss demand us to integrate Scatter-JS In our app mobile application such as iOS, Android .   But we can't find any document or demo to show the user how to implement this . If Scatter-JS support this , give me any information such as demo ,or any OpenSource app on github. Thank you very much!

**Comment by nsjames** [comment]
Well the user doesn't need to implement this at all, only the application. 
`scatter-js` is a replacement for the old way of catching the extension on the `window.scatter` scope.

For `scatter-js` ( single file code ) there's docs up on https://get-scatter.com/docs/dev/setting-up-for-web-apps 

For the new `scatterjs-core` code there's an example here: https://github.com/GetScatter/scatter-js/blob/master/mock-sites/eosjs-esm/main.js

**Comment by nsjames** [comment]
I just added documentation for native socket connections. 
See it here: https://get-scatter.com/docs/dev/setting-up-for-native-apps

**Comment by jacktang** [comment]
@nsjames scatter iOS app is available online?

**Comment by nsjames** [comment]
@jacktang no Scatter is not yet available for iOS.

**Comment by MartinDong** [comment]
Hey , if to support scatter with android just to copy  ' scatter-js/src' all file to android assets and to load that to WebView ?? 
Or, other any way?? Please give us an idea,. Thank you very much!

**Comment by nsjames** [comment]
@MartinDong please see https://get-scatter.com/docs/dev/getting-started

**Comment by jacktang** [comment]
@nsjames we've integrated scatter-js and android. And still some problems here:

1. If scatter wallet app is not install in android phone, how can we know the case?
2. If the wallet is locked, how can we know the case?
3. We unlock the wallet, and going to execute the transaction, and 'accept/deny' UI is shown in notification center. Can we pop up in dapp UI, just like web extension?

Thanks!

**Comment by jacktang** [comment]
@nsjames any plan to support iPhone?

**Comment by ramijames** [comment]
@jacktang Yes, see our roadmap here: https://get-scatter.com/Vision
