### ISSUE TITLE
Does Scatter-Js Adaptive for Safari? 

### ISSUE THREAD

**Issue by shi1234ww** [GetScatter/scatter-js#25]
Hi, We've tested Scatter-Js on Safari . but find it couldn't support DApp which domain contains https .  Is there any solution for this problem ?  Thank you very much !

**Comment by shi1234ww** [comment]
And we used Safari is Desktop version on Mac .

**Comment by nsjames** [comment]
Please see this long thread on local sockets and Safari. 
Until they start following standards there's nothing we can do: https://bugs.webkit.org/show_bug.cgi?id=171934#c32

**Comment by shi1234ww** [comment]
Thank for your reply!

**Comment by nsjames** [comment]
Sorry I can't be of more help there, it's a terrible position they put themselves in. Very frustrating having decentralized innovation held back by corporations :P

**Comment by shi1234ww** [comment]
Hope they will realized these problem Asap.
