### ISSUE TITLE
getArbitrarySignature fails in scatter mobile

### ISSUE THREAD

**Issue by seihyunJeong** [GetScatter/scatter-js#27]
Hello,

I'm using scatter-js and it works fine in scatter chrome extension and scatter desktop.
But when I call getArbitrarySginature() in scatter mobile, the scatter app stones and callback the error.
Other actions work fine including transfer. It seems weird but probably should be updated or be sufficiently tested.

**Comment by nsjames** [comment]
It's possible that that method is still only mocked out on Mobile as it's still in very early prototype alpha. I'm going to close this since it doesn't belong here but you can create a ticket on https://github.com/GetScatter/MobileIssues
