### ISSUE TITLE
HTTP/HTTPS mixed content

### ISSUE THREAD

**Issue by nsjames** [GetScatter/scatter-js#3]
It seems firefox doesn't allow localhost http sockets to https websites citing mixed content.

It's possible that the user's Scatter can generate a self signed cert to use for https connections.

**Comment by jdevora** [comment]
As a temporal work around, you can manually disable the blocking of mixed content in Firefox, 
Click the lock icon on the right side of the address bar.
It will say that Firefox has blocked the unsafe parts of this page
Click the arrow on the right of the message and select 
  "Disable protection for now"

You will need to do this for each pager that you want to interact with Scatter Desktop

**Comment by nsjames** [comment]
Steps to fix for now until I issue a real fix:

- Click the "Lock" icon next to the URL
- Click the "Right Arrow" button
![image](https://user-images.githubusercontent.com/10360675/43952306-369f8fac-9c9e-11e8-8dd1-4313184c79ef.png)

- Click "disable protection for now"
![image](https://user-images.githubusercontent.com/10360675/43952318-42963c98-9c9e-11e8-93eb-bb606240d15f.png)

**Comment by nsjames** [comment]
fixed in 01a9b18967702998a6378450d9499cb8073771f7

Apps should upgrade to 2.1.0

**Comment by docloulou** [comment]
I updated the file on eos.feexplorer.io !
