### ISSUE TITLE
a way to identify when user login to Scatter

### ISSUE THREAD

**Issue by or2008** [GetScatter/scatter-js#34]
Hello, I am building an Eos Dapp using Scatter, and when the app is loaded I check if the user is connected using this line: 

`const isConnected = await ScatterJS.scatter.connect('My App');`

if the user is not connected, I show him a message that tells him to connect.

is there a way to auto detect when the user login? I tried running the above code in interval to check for updates, but it doesn't work so good.

**Comment by nsjames** [comment]
`connect` doesn't log the user in. Here, see this boilerplate. https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs/src/views/Home.vue#L139
