### ISSUE TITLE
SocketService.js:6 WebSocket connection to 'ws://127.0.0.1:50005/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by antbaobao** [GetScatter/scatter-js#35]

**Comment by antbaobao** [comment]
I forgot to install the scatter chrome plugin

**Comment by nsjames** [comment]
For others who are wondering, these errors are normal if the user doesn't have Scatter **Desktop** installed. There's nothing we can do about removing them from the browser's console as those misconnection errors are served by the browsers themselves, and not this library.

**Comment by edwardfhsiao** [comment]
in the docs
```This library catches Scatter Desktop, Scatter Mobile and Scatter Classic ( extension )...```
I thought it means ```scatterjs-core```  could work with any of those versions. 

```scatterjs-core``` doesnt work without desktop version, correct?

**Comment by nsjames** [comment]
It does. The error message is irrelevant.

**Comment by edwardfhsiao** [comment]
Thanks, it worked. But I've encountered a problem is that previously method ```getIdentity()``` returns the name differently.

![image](https://user-images.githubusercontent.com/11728228/47599360-0d5e0500-d9df-11e8-82ba-94127114377c.png)
