### ISSUE TITLE
scatter.isInstalled() throw error

### ISSUE THREAD

**Issue by or2008** [GetScatter/scatter-js#36]
I am looking for a way to check if user installed Scatter Desktop/Extension, I couldn't find a way to do that in the docs, buy I did find, `isInstalled` method on Scatter object. 
is this function reliable and can be used?

anyway, when trying to call it I get this Error:
![image](https://user-images.githubusercontent.com/3414979/46799079-79dcd100-cd5c-11e8-8045-56b7bc9fefdf.png)

**Comment by nsjames** [comment]
Ah actually that method was internal only and deprecated recently since it's redundant. I'll remove it in the next release.

```
ScatterJS.scatter.connect('appname').then(connected => {
    if(!connected){
        // User does not have Scatter installed, or it is not open.
    }
});
```

There is no other way to check if the user has Scatter installed until the next version of Scatter Desktop is released which support opening Scatter with Deep Links.
