### ISSUE TITLE
scatter.eos(network, Eos, eosOptions);  has error 

### ISSUE THREAD

**Issue by magic373** [GetScatter/scatter-js#37]
Eos is not a function now!

the error message:
 TypeError: t is not a function     at t.default.eos (inject.js:40)

**Comment by magic373** [comment]
sorry ,
npm install eosjs ,  again
it's ok

**Comment by apoloShane** [comment]
the same question occurs to me,Just lower vision of eosjs@20 to eosjs@16,
and npm start It works for me. 
Good luck!
