### ISSUE TITLE
Race condition causing Scatter to never connect

### ISSUE THREAD

**Issue by liamcurry** [GetScatter/scatter-js#4]
When using the browser extension, if `ScatterJS.scatter.connect` is called _after_ `scatterLoaded` would've been called then Scatter will never connect and timeout.

I think this code would replicate the issue (untested):

```js
setTimeout(() => {
   ScatterJS.scatter.connect("testing").then(connected => console.log(connected));
}, 10000);
```

The fix would be for the `connect` function to resolve immediately if Scatter has already been loaded/connected.

**Comment by nsjames** [comment]
Doesn't seem to be the case.
I just set a 10 second timeout and it still caught the extension.

**Comment by liamcurry** [comment]
Hm, any idea why I'm seeing this error then?

![image](https://user-images.githubusercontent.com/77758/44003599-e0c382d8-9e22-11e8-8fcb-8e9a67a764f0.png)

**Comment by liamcurry** [comment]
Can you help me debug this issue then? I'm not able to connect to Scatter with `scatter-js` but I can use the web extension fine.

![image](https://user-images.githubusercontent.com/77758/44003717-901fb36c-9e25-11e8-9277-b7a193710f21.png)

I have Scatter Classic installed, and I've tried using `scatter-js/dist/scatter.cjs` and  `scatter-js/dist/scatter.min.js`, same issue with both.

**Comment by nsjames** [comment]
Hit me up on the dev telegram tomorrow and I'll see what we can do

**Comment by MrToph** [comment]
I 'm having the same issue as @liamcurry 
Sometimes the connect promise resolves by timing out after 10 seconds.

Btw, I get the same request failure with status code 0, but this happens even when the promise resolves correctly. But from the code it looks like this is for Scatter Desktop only anyway and I'm testing with the Chrome extension only.

```js
client.js?030d:82 [HMR] connected
polling-xhr.js?9d7b:263 GET http://127.0.0.1:50005/socket.io/?EIO=3&transport=polling&t=MKw0cAi 0 ()
```

Other than that nothing is happening.
I couldn't find a consistent reproduction right now, it fails randomly about 1/3 of the time. I'll see if I can find out something more.

**Comment by nsjames** [comment]
Make sure you are doing `import ScatterJS from..` in your base file ( `main.js` or equivalent, first thing that happens ). That way it sets up the `addEventListener` right when the page loads. 

You don't have to call `.connect` right away, but it should set up the listener first.

This is something I'll have to fix with an interval function in the future to continuously check if scatter classic is loaded onto the DOM, but for now this should work.

**Comment by liamcurry** [comment]
For what it's worth this is also an issue with the web extension. If you bind to the `scatterLoaded` event after it's already been fired then it will seem like Scatter was never loaded. I'm getting around this by simply checking for `window.scatter` before setting up the event listener. Would that be an acceptable solution @nsjames ?

**Comment by liamcurry** [comment]
Looks like this could be implemented here: https://github.com/GetScatter/scatter-js/blob/master/src/scatter.js#L189

This section could be changed to the following (untested):

```js
let holder = new Holder(new Scatter());
if(typeof window !== 'undefined') {
    // Check if extension has already been loaded
    if(typeof window.scatter !== 'undefined') {
        holder.scatter = window.scatter;
        holder.scatter.isExtension = true;
        holder.scatter.connect = () => new Promise(resolve => resolve(true));
    } else {
        window.scatter = holder.scatter;
    }
}

// Catching extension instead of Desktop
if(typeof document !== 'undefined'){
    document.addEventListener('scatterLoaded', scatterExtension => {
        holder.scatter = window.scatter;
        holder.scatter.isExtension = true;
        holder.scatter.connect = () => new Promise(resolve => resolve(true));
    });
}
```

I'm happy to create a PR for this if you approve of this approach.

**Comment by MrToph** [comment]
@liamcurry I tested your code and it works fine. I would vote for this solution as it's more reliable than importing `scatter-js` early and hoping that the `scatterLoaded` event hasn't been fired yet.

**Comment by liamcurry** [comment]
FYI @MrToph @nsjames I created PR #5 to fix this issue. You can try it out with `yarn add sagan-software/scatter-js`.

**Comment by nsjames** [comment]
There's a new version out which should handle this: https://github.com/GetScatter/scatter-js/commit/01d29857af1d26abb96a0e47673d7fbd6e38bcdc

Please pull 2.4.0 and see if it catches late

**Comment by liamcurry** [comment]
I can confirm that 2.4.0 fixes the issue. Thanks!
