### ISSUE TITLE
eosjs2 getting an update

### ISSUE THREAD

**Issue by nsjames** [GetScatter/scatter-js#44]
> 2 helpful takeaways:
- the default export is gone and exports are modified slightly (i.e. new eosjs.Rpc.JsonRpc is now just new JsonRpc)
- JsonRpc now has getRawAbi which retrieves the rawCodeAndAbi.abi and does base64ToBinary, so you can remove your numeric import and use that call instead

**Comment by jafri** [comment]
+1, .transact() failing silently with scatter on eosjs beta 2

**Comment by nsjames** [comment]
This requires a fix for scatter desktop which will come out next release.

( issue was they changed references of `account_name` to `accountName` and broke some scatter internal abi parsing/fetching )
