### ISSUE TITLE
Improve "account not found" error messages when importing keys for EOS chain

### ISSUE THREAD

**Issue by fabifrank** [GetScatter/scatter-js#45]
IMHO it would be helpful to get a better error message when talking to networks. Right now, if you import your keys to the network and the account is set up but the chain is missing the history api plugin Scatter would state that the account was not found, but in fact the endpoint does not exist. Response from eos chain in such cases:
```{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":244,"method":"handle_http_request"}]}}```

**Comment by nsjames** [comment]
Hmm, I'm not sure if we can actually tell the difference. It would be nice if EOSIO gave back a better error itself, but that plugin is being deprecated anyway so I doubt there's going to be any work on it.
