### ISSUE TITLE
Better error message when importing keys for EOS

### ISSUE THREAD

**Issue by fabifrank** [GetScatter/scatter-js#46]
Right now, when you import keys for an identity and the account does exist but the endpoint does not (for example because the network you are talking to does not have the _history api plugin_ enabled) the error message is: "Account not found" but instead it should be "Endpoint not found" like the response from the eos chain.

**Comment by nsjames** [comment]
Please move this ticket to the https://github.com/GetScatter/ScatterDesktop repo as it doesn't belong here.
