### ISSUE TITLE
core: use isomorphic-ws for node.js support

### ISSUE THREAD

**Issue by robertkowalski** [GetScatter/scatter-js#47]
hi and thanks for scatter!

i am writing [sunbeam](https://github.com/bitfinexcom/sunbeam/), a library for both the browser and nodejs. people use it for frontends and also for cli scripts in nodejs.

it would be nice to use isomorphic-ws for the websockets. this way node users can use scatter-js out of the box. right now i have to workaround:

```js
const Websocket = require('isomorphic-ws')
global.WebSocket = Websocket
```

**Comment by nsjames** [comment]
I wonder if this would conflict with normal Websocket implementations and if there's any variance in support. We'll have to do some testing on this to make sure it doesn't break general support as adding this for nodejs apps is a workaround but the opposite might not be true.

**Comment by robertkowalski** [comment]
hi james, thanks for your fast reply!

that makes totally sense! here is the code that is used for the browsers. looks ok for me, for the current usage in scatter at https://github.com/GetScatter/scatter-js/blob/f69ae4eb2414612435e1a1100e5a8e4f1658e019/packages/core/src/services/SocketService.js#L141 the first case is matched and returned: 

https://github.com/heineiuo/isomorphic-ws/blob/da5c99d4bec70d938b0106c43207552cf393e28e/browser.js#L5-L6

**Comment by nsjames** [comment]
Looks good.

Pull `scatterjs-core@2.3.8` which now uses `isomorphic-ws`.
