### ISSUE TITLE
Any ways to push action to call a contract with Scatter?

### ISSUE THREAD

**Issue by randomwork** [GetScatter/scatter-js#51]
Hi. 

I am developing Dapps with Scatter, but I faced the issue that I cannot "push action" to call a contract' function. 
Is there any way to push action with scatter from my Front-end?

Thanks.

**Comment by nsjames** [comment]
Scatter just proxies eosjs under the hood.

https://get-scatter.com/docs/examples-interaction-flow
https://github.com/EOSIO/eosjs/tree/v16.0.9
