### ISSUE TITLE
Use npm scoped packages for Scatter's family of libraries?

### ISSUE THREAD

**Issue by Soleone** [GetScatter/scatter-js#52]
After seeing your `@babel/runtime` instruction in the latest readme, I learned about [scoped packages in npm](https://docs.npmjs.com/misc/scope).

> Scopes are a way of grouping related packages together, and also affect a few things about the way npm treats the package.

I wonder if this might be something you consider for Scatter, e.g. this feature:

> Each npm user/organization has their own scope, and only you can add packages in your scope. This means you don't have to worry about someone taking your package name ahead of you. Thus it is also a good way to signal official packages for organizations.

Then the imports would look something like this potentially:

```
@scatter/core
@scatter/plugin-eosjs
@scatter/plugin-eosjs2
@scatter/plugin-web3
@scatter/plugin-tron
```

Obviously not a priority and managing backwards compatibility might be a bit painful, not sure. Just an idea for sometime in the future maybe.

**Comment by nsjames** [comment]
Indeed this is a good consideration for the future. Especially scope reservation

**Comment by nsjames** [comment]
Given how widely used ScatterJS is now, it would be a breaking change to re-format now sadly.
