### ISSUE TITLE
desktop response is different from chrome extension

### ISSUE THREAD

**Issue by edwardfhsiao** [GetScatter/scatter-js#53]
for example
with chrome extension: 
```js

const eos = ScatterJS.scatter.eos(network, Eos);
eos.transfer.then((trx) => {
    const trxId = trx.transaction_id
)
```

with desktop version v9.5.0:  
```js
const eos = ScatterJS.scatter.eos(network, Eos);
eos.transfer.then((trx) => {
    // trx becomes 'Proxy'
    console.log(typeof trx.transaction_id) // 'function'
)
```

![image](https://user-images.githubusercontent.com/11728228/47895786-41d13580-dea5-11e8-94a1-25b4b53cae6e.png)

currently I have to get the id by ```Object.getOwnPropertyDescriptor(trx, 'transaction_id').value```

am I missing something?

**Comment by nsjames** [comment]
Hmm, is this with the latest version of the plugin-eosjs?

**Comment by edwardfhsiao** [comment]
@nsjames awesome. scatterjs-plugin-eosjs@1.3.9 fixed this.

**Comment by nsjames** [comment]
There's also a 1.3.10 out now which fixed another bug about not propagating the promise catches so you might want to upgrade to that one too.

**Comment by edwardfhsiao** [comment]
@nsjames I'll take a look at it, thanks for the heads-up.
