### ISSUE TITLE
how to commit transaction via using native websocket

### ISSUE THREAD

**Issue by suchengen** [GetScatter/scatter-js#55]
I read the document and find that the document just show me how to create transaction, but I could not get the transcation id from the response. So I think the api just just create transaction without commit ! So how to commit a transaction??
ps: I called create transaction api for my contract to call my function, is that anything wrong? this function has not params
![image](https://user-images.githubusercontent.com/4347553/47988815-3177bf80-e11e-11e8-9adc-1059543a6c64.png)

**Comment by nsjames** [comment]
Scatter itself never commits your transactions, it's up to the application to push them to the blockchain. Scatter only signs them ( and in this case prepares it ).

I can't seem to find my test file which shows the process for this, but the general flow of it is
- createTransaction
- requestSignature
- Push to push signed transaction to blockchain using standard HTTP/POST
