### ISSUE TITLE
my web dapp always  popup : Unlock Request  --- Your Scatter is locked!

### ISSUE THREAD

**Issue by yanlinhust** [GetScatter/scatter-js#56]
but the scatter(destop) is already installed and unlocked.    when i visit the dice.eosbet.io it works. but my web dapp(dc.zhaopeiyu.com) not.

use the scatterjs-core.min.js and scatterjs-plugin-eosjs2.min.js.

**Comment by yanlinhust** [comment]
any step i missed?   my domain must be submitted into the scatter-app gitproject?

**Comment by nsjames** [comment]
Disable the extension from `chrome://extensions`.

**Comment by rmarliere** [comment]
I'm also getting this. 

The connected always returns true when I use the code like in the docs.

`ScatterJS.scatter.connect(configs.appName, connectionOptions).then(connected => {
                // If the user does not have Scatter or it is Locked or Closed this will return false;
                if (!connected) {
                    return false;
                }
            });`
