### ISSUE TITLE
scatter eos hook or proxy provider can not push action to nodeos

### ISSUE THREAD

**Issue by mintzhao** [GetScatter/scatter-js#57]
I am using eosjs2 
``` 
const api = new Api({
        rpc,
        signatureProvider: scatter.eosHook(network),
        textDecoder: new TextDecoder(),
        textEncoder: new TextEncoder()
      });
```
and using api.transact to push an action to the nodeos, but nothing happend, no response, no error.

But If I use eosjs@2.0.0-beta2， and as follows of eosjs document, action can push to the nodeos.

does scatter supoorted eosjs2?

**Comment by nsjames** [comment]
Are you using the `scatterjs-plugin-eosjs2` ?
Can you show me full code in a gist maybe?

**Comment by mintzhao** [comment]
Yes, I'm sure.
code is here:
```
const scatter = await getScatterEOS();
  if (scatter != null) {
    if (scatter.identity) {
      // Always use the accounts you got back from Scatter. Never hardcode them even
      // if you are prompting the user for their account name beforehand. They could
      // still give you a different account.
      const account = scatter
        .identity
        .accounts
        .find(x => x.blockchain === 'eos');

      // Get a proxy reference to eosjs which you can use to sign transactions with a
      // user's Scatter. eosjs2
      const network = {
        blockchain: 'eos',
        protocol: process.env.EOS.PROTOCOL,
        host: process.env.EOS.host,
        port: process.env.EOS.PORT,
        chainId: process.env.EOS.CHAINID
      };

       const api = new Api({
        rpc,
        signatureProvider: scatter.eosHook(network),
        textDecoder: new TextDecoder(),
        textEncoder: new TextEncoder()
      });
      const api = scatter.eos(network, Api, {rpc});

      try {
        const result = await api.transact({
          actions: [
            {
              account: 'xxxx',
              name: 'xxx',
              authorization: [
                {
                  actor: `${account.name}`,
                  permission: `${account.authority}`
                }
              ],
              data: {
                xxxxxx:xxxxx
              }
            }
          ]
        }, {
          blocksBehind: 3,
          expireSeconds: 10
        });
        console.dir(result);
        return result;
      } catch (e) {
        console.log('\nCaught exception: ' + e);
        if (e instanceof RpcError) 
          console.log(JSON.stringify(e.json, null, 2));
        }
      }
  } 
```

If I use hook provider。Console says eosHook is not a function.
If I use proxy provider. Console says TypeError: Cannot read property 'length' of undefined

but if I use eosjs
```
const defaultPrivateKey = 'dddddddd'; // privkey
const signatureProvider = new JsSignatureProvider([defaultPrivateKey]);
const rpc = new JsonRpc(process.env.EOS.JSONRPC, {fetch});
const api = new Api({rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder()});
```
everything is fine!

### env
mac chrome.
scatter desktop and chrome has the same result.

**Comment by nsjames** [comment]
Need more of this code as it's not showing imports for scatterjs, or what `getScatterEOS()` does.

**Comment by mintzhao** [comment]
getScatterEOS() follow the document:https://get-scatter.com/docs/examples-interaction-flow
I think you should must already know what getScatterEOS() does, no need to post more code of it.
And if I didn't imports scatterjs, does the code can go through to the ````const api = xxxxx```,  not a chance.

And I think hook provider show eosHook() not a function, I checked the code of packages/plugin-eosjs2, not a function named eosHook, maybe use hookProvider instead, params of it can fit the document. I will try tonight.

**Comment by nsjames** [comment]
Using `hookProvider` will not work as they are renamed. 

Please post the code inside the `getScatterEOS()` so I can see the full thing. I can't help with only pieces of the code.

Also please post an image of the error that you are getting with desktop open and the extension disabled ( extension does not support eosjs2 )

**Comment by mintzhao** [comment]
I have changed to the scatterjs-plugin-eosjs，and works fine. Great job, thank you
