### ISSUE TITLE
Scatter ledger nano s issue after fairy wallet integration

### ISSUE THREAD

**Issue by micalways** [GetScatter/scatter-js#59]
want to make a transaction with Scatter but I'm stuck.... due to permission changes I can login in Scatter but I am not able to claim, airgrab, make transaction...

code: 402
isError: true
message: "Signature missing error... 

Please help!

**Comment by nsjames** [comment]
Yes, there was a big change with the ledger app without any way for us to make them before the release. If you've updated to the new EOS ledger app you will have to wait for us to support the new app.

**Comment by micalways** [comment]
Thx for your reply, so you are telling me that some development will be done to correct this issue and help us to be able to interact with toolkit again.
To be fair I import my genesis account in the ledger nano s, change active and owner key... boom i am stuck.
