### ISSUE TITLE
Can I use scatter to transfer own coins between test accounts within private chain ?

### ISSUE THREAD

**Issue by wenji-my** [GetScatter/scatter-js#60]
I create the test coin 'SYS' within private chain. I want to transfer some 'SYS' between the test accounts by use scatter api. I use transfer by this code:
       transfer()  {
                const account = scatter.identity.accounts.find(x => x.blockchain === 'eos');
                const opts = { authorization:[`${account.name}@${account.authority}`] };
                eos.transfer(account.name, 'user1', '1.0000 SYS', '', opts).then(trx => {
                    console.log('trx', trx);
                }).catch(err => {
                   console.error(err);
                })
            };

but it throw error with this:
        apigen.js:107 POST http://192.168.1.107:8888/v1/chain/push_transaction 500 (Internal Server Error)
        App.vue:154 trx-err {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[]}}

What's wrong with this code ? Can't scatter transfer private coins within private chain ? or other reason?

**Comment by nsjames** [comment]
That error usually happens from bad `chainId` configs. Can you show me your `scatter.eos()` configuration?

**Comment by wenji-my** [comment]
@nsjames 
````
const network = {
    blockchain: 'eos',
    chainId: 'cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f',
    host:'192.168.1.107',
    port: 8888,
    protocol: 'http'
};
const eos = this.scatter.eos(network, Eos);
...
````

**Comment by wenji-my** [comment]
@nsjames It was my chainId config that was wrong.  I rebuild private chain later, then I forget change the chainId config, I'm so sorry. But it throw new error after I change the config:
````
trx-err {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}
````
What does this mean?

**Comment by nsjames** [comment]
That's a strange error, looks like it's blank and not returning the details of what went wrong. If i remember correctly theres a verbose errors flag in nodeos which you can enable that might allow it to throw more information.

Closing this though, as the original problem is solved.
