### ISSUE TITLE
how to use scatter websocket mod?

### ISSUE THREAD

**Issue by hu272293309** [GetScatter/scatter-js#66]
Hi!
    I don't known, how to use scatter for html5 web applications?
    Looking forward to your reply！
    Thanks！

**Comment by nsjames** [comment]
Check out the mock-sites directory in this repo for plain html/javascript, or the https://github.com/GetScatter/Boilerplates repo for es6 boilerplates.

There's also our documentation here: https://get-scatter.com/docs/setting-up-for-web-apps

**Comment by hu272293309** [comment]
![image](https://user-images.githubusercontent.com/938996/49070693-451ecd80-f267-11e8-9a42-abfcdfa28948.png)
Look it. Was why?

**Comment by hu272293309** [comment]
@nsjames 
I know the reason.
How to install Mobile Scatter in China？
Can you provide a download address for Mobile Scatter?

**Comment by nsjames** [comment]
Scatter Mobile is still very early alpha. 
For now we aren't offering support for it, and for development you should stick to debugging on desktop.
