### ISSUE TITLE
authenticate(12_CHAR_RANDOM_STRING) return same data

### ISSUE THREAD

**Issue by yzhsuper** [GetScatter/scatter-js#68]
I see the document:
scatter.authenticate(12_CHAR_RANDOM_STRING).then(signedOrigin => {
    //...
}).catch(failedAuthentication => {
    // ...
});

It's no use changing the parameters anyway.
It's always return the same data;

how does it work?

English is not my native language; please excuse typing errors.

**Comment by nsjames** [comment]
Are you sure you're passing in a random string of 12 characters length?
I can not reproduce it giving the same results unless the `nonce` that is passed in is the same.

![image](https://user-images.githubusercontent.com/10360675/49316347-5979f900-f4f9-11e8-989a-216ee91cfa64.png)

**Comment by yzhsuper** [comment]
On this website:

**Comment by nsjames** [comment]
If you're validating the data given back which is your domain then it's authenticated.

**Comment by yzhsuper** [comment]
> If you're validating the data given back which is your domain then it's authenticated.

Thank you very much.

And then, The parameter( 12_CHAR_RANDOM_STRING) doesn't work.
It's always use my domain as the parameter, so return same data?


Why are your data different?

**Comment by nsjames** [comment]
`12_CHAR_RANDOM_STRING` needs to be a random 12 character string ( like: `dh2S3k9dJdkx` ) which is the `nonce`. Your domain will also be the `base`, and then a nonce is appended and both are hashed. 

https://github.com/GetScatter/ScatterDesktop/blob/master/src/services/ApiService.js#L145

It will return a signed buffer of 
```
sha256(
    sha256(domain) + 
    sha256(nonce)
)
```

**Comment by yzhsuper** [comment]
> `12_CHAR_RANDOM_STRING` needs to be a random 12 character string ( like: `dh2S3k9dJdkx` ) which is the `nonce`. Your domain will also be the `base`, and then a nonce is appended and both are hashed.
> 
> https://github.com/GetScatter/ScatterDesktop/blob/master/src/services/ApiService.js#L145
> 
> It will return a signed buffer of
> 
> ```
> sha256(
>     sha256(domain) + 
>     sha256(nonce)
> )
> ```
thank you.
I download the ScatterDesktop，and then the 12_CHAR_RANDOM_STRING work，the back data changed。I also verify the back data，it‘’s OK。
But i use the chrome web Extension
[https://chrome.google.com/webstore/detail/ammjpmhgckkpcamddpolhchgomcojkle](url)
it‘’s not work，the back data not changed.
