### ISSUE TITLE
ERROR[7016] in Preact project

### ISSUE THREAD

**Issue by vinstweb** [GetScatter/scatter-js#70]
```
import ScatterJS from 'scatterjs-core';
import ScatterEos from 'scatterjs-plugin-eosjs';
import Eos from 'eosjs';
```
Import any one above in my **Preact** project ，VScode show me ERROR 7016 .
And  chrome-devtools require "ReferenceError: process is not defined".
@babel/runtime is useless.
so, I don't know how to resolve it.
PS: It's OK in VUE and REACT projects.

**Comment by nsjames** [comment]
I'm not familiar with "preact". Did you make any headway on this since opening the ticket?
