### ISSUE TITLE
Cant set contract to a new account

### ISSUE THREAD

**Issue by kstvigilante** [GetScatter/scatter-js#73]
hello,

I create a new account on jungletestnet on a button click in my dapp but i cant set a contract to it , it gives an error Missing required accounts, repull the identity .Is there any way around this ??

**Comment by nsjames** [comment]
Can you post your code?

Generally that error means that one of the authorizations required by the action isn't linked with your dapp.

If you need to accounts ( one to create account + upload contract, and one as the contract account ) you can get two from Scatter by doing `getIdentity({accounts:[network, network]})`
