### ISSUE TITLE
scatterjs-plugin-eosjs2@1.2.0 doesn't work with eosjs v20.0.0-beta3

### ISSUE THREAD

**Issue by tianyangj** [GetScatter/scatter-js#74]
First of all, thanks for this awesome project.

I think there might be a breaking change introduced in eosjs beta3 that requires a fix for plugin-eosjs2. The error I am getting in the console is "ERROR Error: Uncaught (in promise): TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))". However it doesn't tell much. 

After digging into the code, I think eosjs beta3's signatureProvider's sign method is returning of type PushTransactionArgs { signatures: string[]; serializedTransaction: Uint8Array; }. However scatter's sign method is resolving of type string[], https://github.com/GetScatter/scatter-js/blob/master/packages/plugin-eosjs2/src/index.js#L42. What's your suggestion to get around this issue? I am currently downgrading eosjs to beta2, it works perfectly.

**Comment by nsjames** [comment]
There's an open ticket here about this: https://github.com/GetScatter/scatter-js/pull/71

We're still trying to find a good way to implement as it would break some dapps.

**Comment by tianyangj** [comment]
Yes, it is the same issue. I am closing this issue.
