### ISSUE TITLE
无法找到模块“scatterjs-core”的声明文件

### ISSUE THREAD

**Issue by valleylmh** [GetScatter/scatter-js#75]
无法找到模块“scatterjs-core”的声明文件。
“/Users/valley/Codes/react-taro/myApp/node_modules/scatterjs-core/dist/index.js”隐式拥有 "any" 类型。Try `npm install @types/scatterjs-core` if it exists or add a new declaration (.d.ts) file containing `declare module 'scatterjs-core';`

请问scatterjs包可以新增.d.ts的文件这样方便引入使用吗？

**Comment by nsjames** [comment]
There isn't currently any ts support, but will be in the future.
