### ISSUE TITLE
scatterjs-core dependencies were not found

### ISSUE THREAD

**Issue by xumoyan** [GetScatter/scatter-js#76]
`* @babel/runtime/helpers/asyncToGenerator in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/plugins/PluginRepository.js and 2 others
* @babel/runtime/helpers/classCallCheck in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/models/Network.js and 6 others
* @babel/runtime/helpers/createClass in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/models/Network.js and 6 others
* @babel/runtime/helpers/getPrototypeOf in ./node_modules/scatterjs-plugin-eosjs/dist/index.js
* @babel/runtime/helpers/inherits in ./node_modules/scatterjs-plugin-eosjs/dist/index.js
* @babel/runtime/helpers/interopRequireDefault in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/models/Network.js and 6 others
* @babel/runtime/helpers/interopRequireWildcard in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/plugins/Plugin.js and 1 other
* @babel/runtime/helpers/possibleConstructorReturn in ./node_modules/scatterjs-plugin-eosjs/dist/index.js
* @babel/runtime/helpers/slicedToArray in ./node_modules/scatterjs-core/dist/services/SocketService.js
* @babel/runtime/helpers/typeof in ./node_modules/scatterjs-core/dist/services/SocketService.js
* @babel/runtime/regenerator in ./node_modules/scatterjs-core/dist/index.js, ./node_modules/scatterjs-core/dist/plugins/PluginRepository.js and 2 others`

**Comment by nsjames** [comment]
`npm i -D @babel/runtime`

https://github.com/GetScatter/scatter-js#nodejs-and-babelwebpack
