### ISSUE TITLE
scatterjs-plugin-eosjs2 can not proxy eosjs but scatterjs-plugin-eosjs can proxy

### ISSUE THREAD

**Issue by michaellee123** [GetScatter/scatter-js#78]

**Comment by nsjames** [comment]
Need a bit more information about what you're trying to do as well as some errors and maybe example code.

**Comment by nsjames** [comment]
eosjs2 syntax and eosjs1 syntax are very different. 
Check out these boilerplates. 

https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs/src/views/Home.vue
https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs2/src/views/Home.vue

**Comment by michaellee123** [comment]
> eosjs2 syntax and eosjs1 syntax are very different.
> Check out these boilerplates.
> 
> https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs/src/views/Home.vue
> https://github.com/GetScatter/Boilerplates/blob/master/scatterjs-plugin-eosjs2/src/views/Home.vue

I changed my code with this demo, then Scatter Desktop can proxy eosjs signature provider, but now I got a new trouble with transact, same code in there :
```javascript
//init
import ScatterJS, { Network } from 'scatterjs-core';
import ScatterEOS from 'scatterjs-plugin-eosjs2'
import { Api, JsonRpc, RpcError, JsSignatureProvider } from 'eosjs';

ScatterJS.plugins(new ScatterEOS());

const options = { initTimeout: 10000 }
//I useing Jungle TestNet
const network = Network.fromJson({
    blockchain: 'eos',
    protocol: 'https',
    host: 'jungle2.cryptolions.io',
    port: 443,
    chainId: 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473'
})

const rpc = new JsonRpc(network.fullhost());

const requiredFields = { accounts: [network] };
..........
//getIdentity
    window.ScatterJS.scatter.getIdentity(requiredFields).then(identity => {
        window.scatter = window.ScatterJS.scatter
        window.account = window.scatter.identity.accounts.find(function (t) { return "eos" === t.blockchain });
        window.eos = window.scatter.eos(network, Api, { rpc })
    }).catch(err => {
    })
........
//transact
    window.eos.transact({
        actions: [{
            account: 'eosio.token',
            name: 'transfer',
            authorization: [{
                actor: window.account.name,
                permission: window.account.authority,
            }],
            data: {
                from: window.account.name,
                to: 'safetransfer',
                quantity: '0.0001 EOS',
                memo: window.account.name,
            },
        }]
    }, {
            blocksBehind: 3,
            expireSeconds: 30,
        })
        .then(trx => {
            // That's it!
            console.log(`Transaction ID: ${trx.transaction_id}`);
        }).catch(error => {
            console.log(error);
        });
```
When I call the transact function and pass sign with Scatter Desktop, I got a exception message like this:
>TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __values (eosjs-jsonrpc.js:147)
    at arrayToHex (eosjs-jsonrpc.js:175)
    at JsonRpc.eval (eosjs-jsonrpc.js:654)
    at step (eosjs-jsonrpc.js:129)
    at Object.eval [as next] (eosjs-jsonrpc.js:59)
    at eval (eosjs-jsonrpc.js:31)
    at new Promise (<anonymous>)
    at __awaiter (eosjs-jsonrpc.js:8)
    at JsonRpc.push_transaction (eosjs-jsonrpc.js:644)
    at Api.eval (eosjs-api.js:766)

My package.json:
```json
{
    "dependencies": {
        "eosjs": "^20.0.0-beta3",
        "react": "^16.7.0",
        "react-native": "github:facebook/react-native#master",
        "request": "^2.88.0",
        "scatterjs-core": "^2.6.0",
        "scatterjs-plugin-eosjs": "^1.4.0",
       "scatterjs-plugin-eosjs2": "^1.4.0"
      }
}
```
Scatter Desktop Version is v10.0.3

**Comment by nsjames** [comment]
change `window.eos = window.scatter.eos(network, Api, { rpc })` to `window.eos = window.scatter.eos(network, Api, { rpc, beta3:true })`

**Comment by nsjames** [comment]
Also, you should remove things from the `window` scope. 
That allows any plugins to send request to Scatter in your domain's name.

**Comment by michaellee123** [comment]
> Also, you should remove things from the `window` scope.
> That allows any plugins to send request to Scatter in your domain's name.

It's so dope! I called transact function succeed, I'm not a web developer, I just try a demo for support Scatter SDK development for dapps. Thank you so much! I'm happy for you can understand my Chinglish. God bless you! :p
