### ISSUE TITLE
 "There is no identity with an account set on your Scatter instance.", Error with ScatterWebExtension

### ISSUE THREAD

**Issue by johanninos** [GetScatter/scatter-js#82]
with **ScatterWebExtension(Scatter Classic)**

get Error 
```javascript
 {
     type: "There is no identity with an account set on your Scatter instance.",
     message: undefined,
     code: 423,
     isError: true
}
```
when fire `authenticate()` or `logout()` after `getIdentity()`

```javascript
await scatter.getIdentity({
    accounts:[network]
})

scatter.authenticate('something').then(res => console.log(res))
```

with **Scatter Desktop**  it works 

```javascript
await scatter.getIdentity({
    accounts:[network]
})
```

reload()

```javascript
scatter.authenticate('something').then(res => console.log(res))
```
`authenticate()` also works after reload page

**Comment by nsjames** [comment]
Well, the extension doesn't actually have an `authenticate` method so it might be throwing there.
I'd suggest updating to the latest packages which has errors for those cases ("Scatter Extension does not support the `authenticate` method.")

**Comment by johanninos** [comment]
@nsjames thanks,
I realize that is because throwIfNoIdentity() in authenticate() or forgetIdentity(), I'm figuring it out


```javascript
const throwIfNoIdentity = () => {
    if(!publicKey) throws('There is no identity with an account set on your Scatter instance.');
};
```

it would works, if I use window.scatter injected by Extension instead of scatter-js

**Comment by johanninos** [comment]
```javascript
async runBeforeInterfacing(){
    const network = this.context.network;
    if (network) {
        const getId = window.scatter.getIdentity.bind(window.scatter);
        window.scatter.getIdentity = fields => getId(fields ? fields : { accounts: [network] }).then(id => {
            this.context.identity = id;
            return id;
        });

        const suggest = window.scatter.suggestNetwork.bind(window.scatter);
        window.scatter.suggestNetwork = net => suggest(net ? net : network);
    }

    this.holderFns.set(window.scatter);
    this.context = this.holderFns.get();
    this.context.useIdentity = () => { };
    return true;
}
```

there's a modify 2days ago, I'm no sure what
```
this.context.useIdentity = () => { };
```

`useIdentity()` is the method to set identity & publicKey.
but gets` () => {}` now.
codes in ScatterWebExtension:
```javascript
getIdentity(fields = {}){
        return _send(NetworkMessageTypes.GET_OR_REQUEST_IDENTITY, {
            network:network,
            fields
        }).then(async identity => {
            this.useIdentity(identity); 
            return identity;
        });
}
```

```javascript
useIdentity(identity){
        this.identity = identity;
        publicKey = identity ? identity.publicKey : '';
}
```

**Comment by johanninos** [comment]
```javascript
async runBeforeInterfacing(){
    const network = this.context.network;
    if (network) {
        const getId = window.scatter.getIdentity.bind(window.scatter);
        window.scatter.getIdentity = fields => getId(fields ? fields : { accounts: [network] }).then(id => {
            this.context.identity = id;
            return id;
        });

        const suggest = window.scatter.suggestNetwork.bind(window.scatter);
        window.scatter.suggestNetwork = net => suggest(net ? net : network);
    }

    this.holderFns.set(window.scatter);
    this.context = this.holderFns.get();
    this.context.useIdentity = () => { };
    return true;
}
```

there's a modify 2days ago, I'm no sure what
```javascript
this.context.useIdentity = () => { };
```

`useIdentity()` is the method to set identity & publicKey.
but gets` () => {}` now.
codes in ScatterWebExtension:
```javascript
getIdentity(fields = {}){
        return _send(NetworkMessageTypes.GET_OR_REQUEST_IDENTITY, {
            network:network,
            fields
        }).then(async identity => {
            this.useIdentity(identity); 
            return identity;
        });
}
```

```javascript
useIdentity(identity){
        this.identity = identity;
        publicKey = identity ? identity.publicKey : '';
}
```

this is the reason why I have to reload to trigger the `useIdentity()` in the `constructor()` function
before it be covered.

**Comment by johanninos** [comment]
pull request #83

**Comment by nsjames** [comment]
Try grabbing core `2.7.2` and seeing if that fixes it. I think it's just not holding the reference there properly.

I was the [PR](https://github.com/GetScatter/scatter-js/pull/83/commits/d69783bd3eb83136f5683999a61d98446b2e9a62) you issued but not sure if that solves the root problem ( that method was just a fix for the new injected network )

**Comment by nsjames** [comment]
Definitely something funky there.
I went ahead and added the code in your PR into `scatterjs-core@2.7.5` which seems to be the easiest route to fix the issue. 

Thanks <3

**Comment by edwardfhsiao** [comment]
Hi, @nsjames 

I dound a problem that im not sure if its a bug.

Initially get an identity and forget an identity works well with ```scatterjs-core@2.7.7```, but get an identity second time and forget it occurs ```There is no identity with an account set on your Scatter instance.```

```js
import ScatterJS from 'scatterjs-core';

signOut(){
  console.log(ScatterJS.scatter.identity) // returns null
  ScatterJS.scatter.forgetIdentity().then(() => {
})
```
}

problem does not occur with ```scatterjs-core@2.3.8```

**Comment by foxban** [comment]
> Hi, @nsjames
> 
> I found a problem that I'm not sure if it is a bug.
> 
> Initially getting an identity and forget an identity works well with `scatterjs-core@2.7.7`, but get an identity second time and forget it occurs `Uncaught o {type: "There is no identity with an account set on your Scatter instance.", message: undefined, code: 423, isError: true}`
> 
> ```js
> import ScatterJS from 'scatterjs-core';
> 
> signOut(){
>   console.log(ScatterJS.scatter.identity) // returns null
>   ScatterJS.scatter.forgetIdentity().then(() => {
> })
> ```
> 
> }
> 
> problem does not occur with `scatterjs-core@2.3.8`

Same problem here, even using the code from the official docs, any suggestions?
