### ISSUE TITLE
error when using scatter code": 3090003

### ISSUE THREAD

**Issue by Benedictchale** [GetScatter/scatter-js#92]
Hi
I am getting error whenever I try to get airgrab via EOStoolkit or use scatter to login site and making transactions.
Details:
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3090003,
    "name": "unsatisfied_authorization",
    "what": "Provided keys, permissions, and delays do not satisfy declared authorizations",
    "details": [
      {
        "message": "transaction declares authority '{\"actor\":\"ha3diojzhage\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"EOS6oPSjrmopLJybHoRPtEExKigwYZ3TMLyq6CwKRgMSRysNoLWw7\"], and a delay max limit of 3888000000 ms",
        "file": "authorization_manager.cpp",
        "line_number": 520,
        "method": "check_authorization"
      }
    ]
  }
}

plz help; 
(I cannot code)

thanks

**Comment by davidtai** [comment]
I am also seeing this issue when trying to implement the example code eos beta3:

```
{"code":401,"message":"UnAuthorized","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"davidtaiviii\",\"permission\":\"active\"}', but does not have signatures for it.","file":"authorization_manager.cpp","line_number":588,"method":"get_required_keys"}]}}
```

**Comment by nsjames** [comment]
This error generally means you're trying to sign a transaction with an account that doesn't have the proper key inside of Scatter. It is usually cause by either manually putting an account into the transaction instead of using the account from the identity (`ScatterJS.account('eos')`) or when you have manually linked an account inside of Scatter to a private key it doesn't belong to.

**Comment by Benedictchale** [comment]
Thanks James 
what I did was;
 I made new public/pvt keys for active and owner account separately for Telos blockchain, Bloks, worbli etc and replaced them from my genesis keys Telos, Worbli, etc. since then I am getting above mention error.
How can I correct it

**Comment by Benedictchale** [comment]
nsjames plz help what to do next..?

**Comment by nsjames** [comment]
I'm not 100% sure what's going on there. You might get better response time going through our support channels as this isn't developer related and doesn't belong on this repository. 

https://support.get-scatter.com/
