### ISSUE TITLE
scatter.getIdentity() doesnt give the account through which i logged in

### ISSUE THREAD

**Issue by kstvigilante** [GetScatter/scatter-js#93]
i have multiple eos accounts in my scatter desktop , i login using one of the accounts  but when i do
`getIdentity({ accounts:[network] }).then(id => {
    const account = id.accounts[0];
    const options = { authorization:[`${account.name`@`${account.authority`] };
});`

i get an account which is not the same as the one i logged in , also getIdentity() always returns the same account

**Comment by nsjames** [comment]
It sounds like you already have a permission set up for interaction with the site (which is also why there is no longer a popup).

You will have to call `forgetIdentity()` first before issuing another `getIdentity()` request.

**Comment by kstvigilante** [comment]
oh thanks :)
