### ISSUE TITLE
Using the extension 6.2.0 and the eosjs v20.0.0-beta3 I cannot execute the boilerplate

### ISSUE THREAD

**Issue by boymaas** [GetScatter/scatter-js#95]
![image](https://user-images.githubusercontent.com/300333/52920077-216ca000-3309-11e9-9e17-a9c0c85ba2e7.png)

Executing boilerplate example, after successful connect and login, i get an error on the following line:

![image](https://user-images.githubusercontent.com/300333/52920119-6f81a380-3309-11e9-8659-a409d59feaa8.png)

Error in console (Chrome)

![image](https://user-images.githubusercontent.com/300333/52920127-80321980-3309-11e9-9cfd-64e90b4b4f71.png)

Code location, extension inject.js:

![image](https://user-images.githubusercontent.com/300333/52920134-9b048e00-3309-11e9-88fa-b629ebfeeed5.png)

where **w** is instantiating a proxy object, calling the passed Api object as a function.

![image](https://user-images.githubusercontent.com/300333/52920188-3138b400-330a-11e9-898e-2699d8f9b651.png)

Been struggling with this for a while, help greatly appreciated. Beginning to believe that the Chrome extension is not being supported anymore, is this the case?

**Comment by nsjames** [comment]
Extension does not support eosjs2.

You can either move to eosjs1 or use desktop.
