### ISSUE TITLE
Cannot re-initialize scatter for a second time with the extension version

### ISSUE THREAD

**Issue by edwardfhsiao** [GetScatter/scatter-js#99]
I know the extension version is not recommended using any longer, but something wrong when trying to re-initialize scatter for a better network connection.

![screen shot 2019-02-27 at 10 02 40 am](https://user-images.githubusercontent.com/11728228/53460149-13d8b800-3a77-11e9-9821-a1d40eb7b076.png)
```js
    "eosjs": "^16.0.9",
    "scatterjs-core": "^2.7.14",
    "scatterjs-plugin-eosjs": "^1.5.1"
```

```js
const network = [{...}, {...}]

const initScatter = index => {
  console.log('init start');
  ScatterJS.scatter.connect('APP_NAME').then(connected => {
    console.log('something wrong here');
    if (!connected) {
      return false;
    }
    ScatterJS.scatter.eos(network[index], Eos);
    return true;
  });
};

initScatter(0)

document.getElementById('networkIndexSelection').addEventListener('change', e => {
  const index = e.currentTarget.value;
  document.getElementById('networkIndex').innerHTML = index;
  initScatter(index);
});
```

when I tried to change the index to re-initialize the scatter,  occurs
`Extension.js:1 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined`

Ony with the EXTENSION version.

https://github.com/edwardfhsiao/scatter-test-repo

```sh
npm i
```
then 
```sh
npm run server
```

0.0.0.0:3000

**Comment by edwardfhsiao** [comment]
![screen shot 2019-02-27 at 10 02 40 am](https://user-images.githubusercontent.com/11728228/53460108-f73c8000-3a76-11e9-8ac2-fe964055048a.png)

**Comment by nsjames** [comment]
Try updating to the latest versions. I think this was something we recently fixed.

**Comment by edwardfhsiao** [comment]
the problem remains with 2.7.16

**Comment by nsjames** [comment]
Hard to tell with just the error msg and no line details, but I think it might be one of the lines that includes `this.holderFns.get()`

Can you try downgrading core to `2.7.6` and seeing if that fixes it?

**Comment by edwardfhsiao** [comment]
Yes,```2.7.6``` does not occur problem

**Comment by nsjames** [comment]
Okay, so I'm guessing it has something to do with the new `ScatterJS.wallet` naming system. 
Let me run some tests and I'll see if I can issue a fix pronto.

**Comment by edwardfhsiao** [comment]
Sure thing, take your time.

**Comment by nsjames** [comment]
Actually, wait.

**Comment by nsjames** [comment]
You shouldn't be trying to re-connect to Scatter. I think the login flow there is just wrong which is causing it to bust.


1: ScatterJS.connect(...) <-- **Only once for the entire page**
2: ScatterJS.login(...)
3: eos = ScatterJS.eos(...)


The `ScatterJS.connect` should only happen at the top-level of your javascript document. When you try to do that again later it no longer has the ability to bind and catch a reference for wallet injections which is what the extension and most mobile wallets are doing.

You also need to do `ScatterJS.login()` or `ScatterJS.getIdentity()` (both are just aliases) before you bind an `eos` instance or there will be no signature provider allow to connect to Scatter.

**Comment by nsjames** [comment]
```
const network = [{...}, {...}]

let connected = false;
let eos;
ScatterJS.scatter.connect('APP_NAME').then(c=> {
    connected = c;
    if (!connected) {
      return false;
    }

    initScatter(0);
});

const initScatter = index => {

    eos = ScatterJS.scatter.eos(network[index], Eos);
    return true;
};

document.getElementById('networkIndexSelection').addEventListener('change', e => {
  const index = e.currentTarget.value;
  document.getElementById('networkIndex').innerHTML = index;
  initScatter(index);
});
```

**Comment by nsjames** [comment]
You still need login functionality in the snippet above which needs to be handled.

**Comment by edwardfhsiao** [comment]
Okay, now I understand. Thank you @nsjames

**Comment by edwardfhsiao** [comment]
@nsjames Sorry to bother you, but with the code you provide above, works great with extension but not the desktop version.
```index.js:1 Uncaught (in promise) TypeError: b.isValid is not a function```

Can you take a look? The code still here https://github.com/edwardfhsiao/scatter-test-repo

**Comment by edwardfhsiao** [comment]
switching the order of ```eos = ScatterJS.scatter.eos(network[index], Eos)``` ,```ScatterJS.getIdentity()``` prevent the error log, but somehow ```eos``` instance never binded

**Comment by edwardfhsiao** [comment]
Okay, it is the problem of the version of scatterjs-plugin-eosjs
